### ISSUE TITLE
[BUG]Strange Blank

### ISSUE THREAD

**Issue by ghost** [vonhyou/theme_toReality#2]
![image](https://user-images.githubusercontent.com/8530043/104326483-bf346e00-5524-11eb-9190-807f646767ce.png)
Here is a big blank, which did not appear before the latest commit ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by vonhyou** [comment]
This bug could become a legacy and I moved it to a new [branch](https://github.com/vonhyou/theme_toReality/tree/pjax)
